package enums;

public enum Plurality {
	PLURAL,
	SINGULAR,
	BOTH,
	FIRST_PERSON_SINGULAR_PRONOUN,
	THIRD_PERSON_SINGULAR_PRONOUN,
	FIRST_PERSON_PLURAL_PRONOUN,
	SECOND_PERSON_PLURAL_PRONOUN,
	THIRD_PERSON_PLURAL_PRONOUN
}
